#!/usr/bin/perl -w 
use strict;

my ($dir) = @_;
my @files = glob "*.html";
my $fl;
foreach my $efile (@files) {
    open(FILE, "<" . $efile);
    while(<FILE>) {
	#s/www.dezearch.com/localhost/;
	#s/holley\@iee\.org/sales\@dezearch\.com/;
	#s/plating_plant/plant_sim/;
        #s/localhost/www\.cloudsandangels\.com/;
	#s/localhost/192\.168\.1\.3/;
	#s/192\.168\.1\.3/localhost/;
	s/localhost\\home/polarbear\web\dezearch/;
	 $fl .= $_;
    }
    print $fl;
    close FILE;
    open(FILE, ">" . $efile);
    print FILE $fl;
    $fl ="";
#    print $fl;
    close FILE;
}
exit(0)

